--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/larryTheCoder/SkyWarsForPE 
branches:
- master
projects:
  SkyWarsForPE:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.0
      - src: https://poggit.pmmp.io/r/92648/JasonDB_dev-1.phar
        vendor: raw
...
