name: SkyWarsForPE
main: larryTheCoder\SkyWarsPE
version: "3.1.30-BETA"
api: 3.0.0+ALPHA9
author: larryTheCoder
website: https://github.com/larryTheCoder/SkyWarsForPE
softdepend:
  - EconomyAPI
  - EasyKits
extensions:
  - sqlite3
commands:
  sw:
    description: main skywars command
    default: true
    permission: sw.command
permissions:
  sw.command.lobby:
    description: back to main lobby
    default: true
  sw.acces:
    description: access the game intrance
    default: true
  sw.editlobby:
    description: prevent players from edit lobby
    default: op
  sw.sign:
    description: join using signs 
    default: true
  sw.command:
    description: allow player to use all skywars command
    default: true
    children:
     sw.command.random:
        description: Randomly teleport to a game
        default: true
     sw.command.help:
        description: get SkyWars help menu
        default: true
     sw.command.setlobby:
        description: set SkyWars main lobby
        default: op
     sw.command.create:
        description: create a SkyWars arenas
        default: op
     sw.command.reload:
        description: reload skywars plugin
        default: op
     sw.command.start:
        description: start a game
        default: op
     sw.command.stop:
        description: stop a game
        default: op
     sw.command.delete:
        description: delete a arena
        default: op
     sw.command.set:
        description: set an arena
        default: op
     sw.command.join:
        description: join to arena
        default: true
     sw.command.kick:
        description: kick a player from game
        default: op
