name: SkyWarsForPE
main: larryTheCoder\SkyWarsPE
version: "3.1.32-BETA"
api: 3.0.0+ALPHA9
author: larryTheCoder
website: https://github.com/larryTheCoder/SkyWarsForPE
softdepend:
  - EconomyAPI
  - EasyKits
extensions:
  - sqlite3
commands:
  sw:
    description: main skywars command
    default: true
    permission: sw.command
permissions:
  sw.command.lobby:
    description: Teleport player back to main lobby.
    default: true
  sw.moderation:
    description: SkyWars moderation permission, allow moderation in-game.
    default: op
  sw.command:
    description: Allow player to use all skywars command
    default: true
    children:
      sw.command.random:
        description: Randomly teleport to a game.
        default: true
      sw.command.help:
        description: SkyWars help menu.
        default: true
      sw.command.setlobby:
        description: Set SkyWars main lobby location.
        default: op
      sw.command.create:
        description: Create a new SkyWars arena.
        default: op
      sw.command.start:
        description: Start a SkyWars arena
        default: op
      sw.command.stop:
        description: Stop a SkyWars arena
        default: op
      sw.command.set:
        description: Settings an arena.
        default: op
      sw.command.join:
        description: Join to an arena.
        default: true
      sw.command.kick:
        description: Kick a player from an arena.
        default: op
