###########################################################################################
# This is a YML file. Be careful when editing. Check your edits in a YAML checker like    #
# the one at http://yaml-online-parser.appspot.com                                        #
###########################################################################################
---
# This version section is to verify this
# config file.
version: 1

# ---
# Welcome to SkyWarsForPE arena.yml game file. Here you can edit whatever the stuff you
# want to to make your skywars game interesting. You can also use any supported custom GameAPI
# for this config too.
# ---

# You can disable this arena by setting this to false
enabled: true
# Pick your own arena name.
arena-name: "Beast World"
# The mode of the arena.
#  0 - Solo
#  1 - Team
arena-mode: 0

# Related to teammate settings
# If arena-mode is set to '1'.
#
# WARNING:
#   THIS WILL OVERRIDE THE ARENA SETTINGS
#   THAT HAS BEEN SET. PLEASE REFER HERE
#   IF YOU SET ARENA MODE INTO 1.
team-settings:
  # The number of players needed
  # For a team.
  players-per-team: 3
  # This decides either the player has
  # the permission to choose their own team
  # or they will get random team. The player
  # will have a set of colors in their inventory
  # hotbar if this is set to false.
  monarchy-system: false
  # The number of teams in this game.
  # You must have this set to make sure that the
  # plugin can work properly.
  world-teams-avail: 3
  # The minimum number of players needed
  # for the arena to start it.
  minimum-teams: 2
  # Interactive spawns mean that if you have this enabled
  # The arena will put all of the team members in the same cage.
  # Otherwise, the players will be placed into isolated cages.
  interactive-spawns: false

# Lobby settings
# [Game-API related features]
lobby-settings:
  # Enable lobby functions. If you enable this. All the players
  # Will be teleported to a world where that has been set as a lobby.
  # And when the game has started. They will be teleported to their cages.
  # Recommended for a game that requires teams.
  enable: false
  # The lobby spawn location
  join-lobby-x: 89
  join-lobby-y: 78
  join-lobby-z: -487
  join-lobby-world: "Virginia"
  # After the countdown is 0. This is another countdown
  # after the players has been teleported to their cages.
  # Then this number takes place on how long they will be
  # released from their cages.
  release-countdown: 10

# The game sign section
signs:
  # These are the coordinates for your
  # Join sign, including the world name
  join-sign-x: 89
  join-sign-y: 78
  join-sign-z: -487
  join-sign-world: "world"
  # To enable the status sign
  # Please ensure that this will be enabled
  # Otherwise the sign wont tick
  enable-status: true
  # Status lines for signs.
  # Variables:
  #   &a &b &c = you can use color with "&"
  #   %alive = amount of in-game players
  #   %dead = amount of dead players
  #   %status = game status
  #   %world = world name of arena
  #   %max = max players per arena
  #   %name = The name of this arena as 'arena-name'
  status-line-1: "&8[&cSkyWars&8]"
  status-line-2: "&a%name"
  status-line-3: "&7Players: &2%alive&3/&2%max"
  status-line-4: "%status"
  # Sign will update every 'x" seconds
  # The 'x' is depends on this section.
  # This effects the client connections.
  sign-update-time: 1

# The chest configuration config
chest:
  # You can set either want to refill
  # The chest arena after 'refill-rate' or
  # Not
  refill: true
  # Refill average. The arena wil pick a random number
  # Within these numbers to refill the chests.
  refill-average: [240, 332, 120, 50, 81, 85, 90]

winners:
  # Here is the command configuration for each winners.
  # Please make sure you config this correctly, this data here is for
  # Player who were in the 1st place. The wildcards are as follows:
  # %p - The player name
  # %s - The arena name
  - command-execute:
      - "givemoney %p 300"
      - "addkarma %p 50"

  # Here is for the player who is on the second place.
  # ~And so on.
  - command-execute:
      - "givemoney %p 150"
      - "addkarma %p 25"

# The arena section
arena:
  # Arena game location
  # Make sure you put the name correctly!
  arena-world: "SkyWarsForPE"
  # The spectator spawn
  # No level were given here because the
  # Spectator usually be summon at 'arena-world"
  spec-spawn-x: 320
  spec-spawn-y: 50
  spec-spawn-z: 32
  # The Grace timer,
  # This can avoid the player to be killed too,
  # Soon, when falling from spawn pedestals.
  grace-time: 5
  # Spectator mode,
  # You can have spectators in the arena,
  # Otherwise set this to false.
  spectator-mode: true
  # Daytime cycle,
  # This 'Daytime Cycle' can determinate,
  # If you want the arena to 'tick' the level,
  # Or not. Set to true if you want to 'tick' the level.
  # USE-ONLY: (true / day / night / [ticks]).
  time: "day"
  # Reward for winner,
  # Put any value for it, make sure
  # You have EconomyAPI plugin setup.
  money-reward: 20
  # Finish message level / world
  # If you want to broadcast to every world, set this to 'all'
  # Format: "level-a:level-b:level-c" - ':'
  finish-msg-levels: "world:deviantart:joshuaa"
  # Start when the arena is full
  # for me, I will do `true`
  start-when-full: true
  # Max players in arena
  max-players: 12
  # Min player in arena
  min-players: 2
  # Starting time (seconds)
  starting-time: 60
  # Spawn positions in arena
  spawn-positions:
    pos-1: "127:56:128"
    pos-2: "130:56:129"
    pos-3: "129:56:126"
    pos-4: "121:56:122"
    pos-5: "126:56:133"
    pos-6: "126:56:133"
    pos-7: "126:56:133"
    pos-8: "126:56:133"
    pos-9: "126:56:133"
    pos-10: "126:56:133"
    pos-11: "126:56:133"
    pos-12: "126:56:133"